spring:
  application:
    name: kafka-avro


#  kafka:
#    bootstrap-servers: "127.0.0.1:9092"
#    producer:
#      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
#      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
#      properties:
#        schema:
#          registry:
#            url: "http://127.0.0.1:8081"
#    consumer:
#      group-id: "my-topic"
#      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
#      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
#      autoOffsetReset: "earliest"
#      properties:
#        schema:
#          registry:
#            url: "http://127.0.0.1:8081"
#        specific:
#          avro:
#            reader: "true"


app:
  kafka:
    topic: avro-topic
    group-id: consumer-group-id

server:
  port: 8000
