spring:
  application:
    name: authentication-service
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    username: admin
    password: admin
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
jwt:
  secret: 84e92f3e89924ee4c2a2cd4739b9e06496179a126512e59e
server:
  port: 8080
